[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.floorandcarpetsmx.com/*"
  to = "https://floorandcarpetsmx.com/:splat"
  status = 301
  force = true